

python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 01 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 02 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 03 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 04 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 05 &

wait

python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 06 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 07 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 08 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 09 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 10 &

wait

python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 11 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 12 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 13 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 14 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 15 &

wait

python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 16 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 17 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave.py 18 &

wait

# for runs at cartesius
# killall -u edwinhs
