

python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 01 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 02 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 03 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 04 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 05 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 06 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 07 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 08 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 09 &

wait

python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 10 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 11 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 12 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 13 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 14 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 15 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 16 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 17 &
python 0_main_analyze_discharge_for_pcrglobwb_only_from_1901.py 18 &

wait

# for runs at cartesius
# killall -u edwinhs
